# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caf01a76031cf5353066b60dcca3ab6ce58556bf530a0e41ed97976cc5a2e2692df9322c47b90ca095b3ab6203c0daa76fcb6a2a023588a7ee246d8a93d5d8a8

test:
  secret_key_base: 1f4acbe91fb4038e6d65b1b576adefb668d824668e0dd17d53aa561c2a42fe1bcad7ca6e3b4b5e2a7714d30d8105d672a94656488b1342d820f8545079eb5820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
